.gitignore, Cargo.toml, README.md, build.rs, examples/simple_example.rs, rustfmt.toml, src/lib.rs, src/traceme.c
Here is a small Rust library to trace any given pid with Intel PT.
It's just enough to get us going:
```
fn main() {
let mut res = 0;
let pid = unsafe { getpid() };
let mut tracer = Tracer::new().trace_filename("simple_example.ptt");
tracer.start_tracing();
for i in 1..10 {
res += i + pid;
}
tracer.stop_tracing();
println!("result: {}", res);
}
```
* Calls to C, storing the C state behind an opaque pointer.
* For now writes trace to file (long term, to memory buffer).
* If something goes wrong, panic (long term, `Result`s).
* Doesn't make any attempt to pre-prime the tracer.
* All public stuff documented.
* Linted with Clippy.
* Formatted with rustfmt.
* Debugging statements left on for now.
Typical debug output:
```
$ sudo ./target/debug/examples/simple_example
src/traceme.c:345 …
```
=> The Basics

analyse.mk, build.rs, src/lib.rs, src/traceme.c
This replaces all of the `err()` and `errx()` calls with error propagation.
It's quite a big change. Sorry about this. It's been a thing of nightmares to get this right. 
In short, I've minimised the amount of sharing between threads so that it becomes clear(er) by design who should be freeing/closing what.
I've tested by inserting artificial errors into the code at various places and checking the Rust assertions fire. I'm also going to try some static/dynamic analysers on this to see if we can tease out more bugs.
So while I am doing that, can you see anything obviously wrong with this?
Rust error handling will come as a separate PR (did you read the error handling section of the rust book btw?)
Cheers
=> Error handling for the C code.

examples/simple_example.rs, src/errors.rs, src/lib.rs
By using a `String` until the last moment when we hand off to C, we can avoid early `NulErrors` and also simplify `make_map_filename` quite a bit.
While we are here, check the trace filename ends in `.ptt`, and add a very basic test.
Makes sense?
=> Simplify trace_filename error handling and ensure it has a `.ptt' extension.

src/errors.rs, src/lib.rs, src/traceme.c
This change:
* Checks we have permission to trace.
* Ensures the `ptt` and `map` files are created with appropriate permissions.
Looks good?
Fixes #7
=> Check we have permission to trace, and fix file permissions.

.travis.yml, build.rs, feature_checks/check_perf_pt.c, src/backends/dummy.rs, src/backends/mod.rs, src/backends/perf_pt/mod.rs, src/backends/perf_pt/perf_pt.c, src/errors.rs, src/lib.rs
To begin with we have "pt_perf" and "dummy" backends.
* pt_perf uses Linux Perf to collect Intel Processor Trace packets.
* dummy is a fall-back backend which does nothing.
Conditional compilation is used to include/exclude the pt_perf backend
depending upon the the outcome of a (crude) feature check in build.rs.
It's up to the consumer if traceme to choose an appropriate tracing backend and configure it (instantiation and configuration is specific to each tracer, and not part of the `Tracer` trait).
Note that the compiler output appears for failing feature checks appear in the `cargo build` output (and so in the travis log too). A bit annoying, but not a show stopper. I'm hoping the Rust community will devise a better feature check mechanism in the future.
Looks good?
Fixes #10, #16, …
=> Introduce "tracing backends" into traceme.

src/backends/perf_pt/mod.rs, src/backends/perf_pt/perf_pt.c, src/errors.rs, src/lib.rs, src/util/mod.rs, src/util/util.c
This kills the "stashing of the map file" and the crufty code around it.
Instead of copying a file out of procfs (which relies on the OS having proc, and would have to be sucked in and parsed later), we use the semi-portable `dl_iterate_phdr()` API to work with in-memory data structures. This also helps with tests, since the map flie is one less file to race in parallel testing (the trace file still races -- fixing in #8).
The new code isn't used (apart from in tests), but will be needed later to relate PT packets to the binary code.
Looks good?
=> Kill map file

examples/simple_example.rs, src/backends/perf_pt/mod.rs, src/errors.rs
A few bits detected by clippy.
I didn't accept all of clippy's advice. Here are the ones I think I'd rather *not* implement:
```
warning: you should consider deriving a `Default` implementation for `backends::dummy::DummyTracer`
--> src/backends/dummy.rs:48:5
|
48 | /     pub fn new() -> Self {
49 | |         Self {started: false}
50 | |     }
| |_____^
|
= note: #[warn(new_without_default_derive)] on by default
= help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.177/index.html#new_without_default_derive
help: try this
|
42 | #[derive(Default)]
|
Finished dev [unoptimized + debuginfo] target(s) in 0.26 secs
example: simple_example
Compiling traceme v0.1.0 (file:///home/vext01/research/traceme)
warning: unneeded return statement
--> …
```
=> Misc tidying

README.md, src/backends/perf_pt/mod.rs, src/backends/perf_pt/perf_pt.c, src/util/mod.rs, src/util/util.c
For the perf_pt backend, we want to trace a thread ID (TID), not a
process (PID). A TID is a Linux specific notion, and unfortunately pid_t
is re-used for TIDs, which can lead to some confusion. I've updated doc
strings to try and make it clear to users.
The example code worked because the first thread of a program has the same TID as the PID. `cargo test` however, spawns a thread (with a new TID). We were tracing the main thread that's sat there twiddling it's thumbs waiting for the test thread to exit.
We can see the issue by looking at the debug output before and after this fix.
Before:
```
test backends::perf_pt::tests::test_basic_usage ...
...
rc/backends/perf_pt/perf_pt.c:220 [poll_loop]: wake
src/backends/perf_pt/perf_pt.c:221 [poll_loop]: aux_head=  0x0000000000 …
```
=> Fix a bug where perf_pt tests don't receive any trace data.

.travis.yml, Cargo.toml, analyse.mk, examples/simple_example.rs, src/backends/dummy.rs, src/backends/perf_pt/mod.rs, src/backends/perf_pt/perf_pt.c, src/lib.rs
This change allows us to trace to memory buffers, instead of files.
* In doing so, we've allowed the tests to run in parallel. 
* Once the trace pops out of C code, we say the underlying buffer is owned by `HWTrace`, hence we have a `drop` to free the buffer when it falls out of scope.
* valgrind is happy
* `HWTrace` will be a trait soon, as discussed.
* A couple of semi-related bits in separate commits.
Please fire away with questions. I expect you will have loads.
=> Trace to memory

examples/simple_example.rs, src/backends/dummy.rs, src/backends/perf_pt/mod.rs, src/backends/perf_pt/perf_pt.c, src/errors.rs, src/lib.rs
This change makes the tracers efficiently re-usable.
Get some popcorn, because there's a bit of back-story before you can review.
In short, before we would `perf_event_open()` a new perf fd and `mmap()` our buffers every time we started tracing. This is inefficient as these can be re-used over and over. This change fixes that.
However, it comes with an API change which I didn't appreciate until implementing this. Before we had:
```
let tracer = PerfPTTracer::new().target_tid(12345).aux_bufsize(64);
tracer.start();
... work
let trace = tracer.stop()
```
Now that the tracer is re-usable, under this interface, the user might think they can re-configure the tracer before subsequent calls to `start_tracing()`:
```
let tracer = PerfPTTracer::new().target_tid(12345).aux_bufsize(64); …
```
=> Make the IPT tracer re-usable and document the mmap(2) dance.

src/backends/dummy.rs, src/backends/perf_pt/mod.rs, src/lib.rs
This change (as discussed earlier somewhere) uses a generic type for traces coming from different backends.
Looks good?
=> Use a trait for traces, so that different backends can return different traces.

README.md, build.rs, c_deps/.gitignore, c_deps/Makefile, src/backends/perf_pt/decode.c
This is the {fetch and build, use system} libipt build system change we discussed the other day.
No functional change. In preparation for decoding IPT traces. Dummy code is included to check linkage works.
Tested with/without bundled build of libipt.
Looks good?
=> Depend on libipt.

src/backends/perf_pt/collect.c, src/backends/perf_pt/mod.rs
This is the first of a few fixes coming in to make the trace decoding branch work.
This fixes #41. Please see the issue for a description of why this change is required.
The doc test change is weird. Only after the first commit does it crash. It should have been crashing all along. For what reason, I don't know. Anyway, it's fixed now.
OK?
=> Ensure traces start with a `PSB+` packet sequence.

Cargo.toml, README.md, build.rs, c_deps/Makefile, examples/simple_example.rs, src/backends/dummy.rs, src/backends/perf_pt/collect.c, src/backends/perf_pt/decode.c, src/backends/perf_pt/mod.rs, src/backends/perf_pt/perf_pt_private.h, src/backends/perf_pt/test_helpers.c, src/lib.rs, src/util/mod.rs
This adds support for block decoding into the perf_pt backend.
It's a large change and I'm pretty certain you will be able to find some nits! Let the discussion begin!
Anything `XXX` is either Rust/Cargo bugs/limitations, or something which I think can be tackled later in later PRs.
Fixes #28
=> Block decoding support.

src/backends/dummy.rs, src/backends/perf_pt/mod.rs, src/errors.rs, src/lib.rs
This refactors the error handling as we discussed the other day.
I'm only dealing with Rust-level errors at this time, C-level errors will follow. See the `XXX`.
I'm still questioning weather the "fatal" / "non-fatal" distinction is useful. Is "common to all backends" / "not common to all backends" a better distinction?
Thoughts?
=> Errors Part 1

build.rs, examples/simple_example.rs, src/backends/perf_pt/collect.c, src/backends/perf_pt/decode.c, src/backends/perf_pt/mod.rs, src/backends/perf_pt/test_helpers.c, src/backends/perf_pt/util.c, src/errors.rs
This implements a error handling scheme for the perf_pt backend which is capable of communicating libipt and errno style errors.
Instead of just returning "something went wrong", we now set a type and code using `perf_pt_set_err`, which Rust then converts into a high-level error type.
It took a little longer than expected due to some fiddly cases.
Notes:
* First commit is an unrelated OCD fix.
* The overflow case is now properly handled, rather than being munged together with all other errors. So now we can know when to retry.
* Removed an error indicator from a function which cannot fail  (`read_aux()`).
* Fixed a NULL pointer dereference (I'll point this out).
* Added a field into the tracer context to store errors that can occur inside the thread. It needs to live here so that the …
=> Proper C Error Handling.

src/backends/perf_pt/collect.c
This struct is out of sync with the Rust side.
Although we never use it by value, we should avoid any surprises by bringing it into sync.
Here's the Rust equivalent:
https://github.com/softdevteam/hwtracer/blob/cc3b2229cae51118163a81c7aeb2c7641f146075/src/backends/perf_pt/mod.rs#L313-L326
=> Add a missing struct field on the C side.

examples/simple_example.rs, src/backends/dummy.rs, src/backends/perf_pt/mod.rs, src/lib.rs
As discussed on mattermost, this was once needed, but no more. As you can see the `destroy` methods don't really do any clean up at all.
OK?
=> Kill the explicit destroy in the Tracer API.

build.rs
This means that anything that uses hwtracer inherits the linker path needed to find libipt. It also works transitively, so `hwtracer -> yorickrt -> your_interpreter` works.
OK?
=> build.rs: Use an absolute dep path so consumers inherit a valid path.

Cargo.toml, build.rs, src/backends/perf_pt/mod.rs
This PR makes things build on OpenBSD and updates several dependencies. Mostly these are easy but two (gcc -> cc; and tempfile 2.* to 3.*) require minor code changes.
This passes all tests on bencher8 (except `backends::perf_pt::tests::test_block_iterator5` which it skips, presumably intentionally?).
=> Build fixes

examples/simple_example.rs, src/backends/perf_pt/decode.c, src/backends/perf_pt/mod.rs, src/lib.rs
This will break our yk repo, so I'll have to raise a "companion" PR with this to fix that. However, there's currently some other stuff going on on the yk repo, so let's wait until that's finished. However, we can start the review in the meantime.
The current name for these variables suggests that they give the range
of the block, which would allow to calculate the next block by adding
together `start_vaddr` and `len`. This is not the case though, since len
is calculated from `block.end_ip` which returns the address of the last
instruction in this block. This means that a block with a single
instruction would have a `len` of 0, which is unintuitive.
This commit renames the variables to `first_instr` and `last_instr` and
changes the latter to return the addresses of the last instruction of …
=> Rename start_vaddr and len

src/backends/perf_pt/mod.rs
Another compilation error that somehow slipped CI. I don't get it...
Did we perhaps manually merge in a time where CI was down?
=> Fix compilation error in tests.

src/lib.rs
It's no longer needed and its presence breaks hwtracer on bleeding edge rustc/ykrustc.
=> Remove #![feature(optin_builtin_traits)].

src/backends/perf_pt/mod.rs
It's possible for PerfPTThreadTracer to be dropped while it is still
tracing, leaving the PT tracer running. This can cause issues with other
threads wanting to trace. Calling stop_tracing on the PT tracer when the
hardware tracer is dropped fixes this.
=> Stop tracing upon drop.

build.rs, c_deps.mk, src/backends/perf_pt/decode.c
Upstream libipt merged a branch that was blocking the fixing of a workaround, so we can now pull that in and remove the workaround.
While we are here, update all of the C dependencies, and libipt moved on github too, so use the new URL.
Tested the `yk` repo. All is well.
=> Kill ipt hack

examples/simple_example.rs, src/backends/perf_pt/mod.rs, src/lib.rs
Namely:
- `#[link_args]` has been removed from Rust and it's no longer needed.
- `panic!(format!(..))` is an error in the latest Rust.
=> Make hwtracer build with the latest Rust nightly.

bors.toml, build.rs, src/backends/dummy.rs, src/backends/perf_pt/mod.rs, src/block.rs, src/errors.rs, src/lib.rs, src/test_helpers.rs
A slightly rag-bag set of commits that aim to make the hwtracer crate a bit easier to work with: separating code out into separate files; and removing what, in retrospect, is unnecessary complexity. This PR manages to delete more code than it adds!
Note I have tested this PR with `yk` and everything still builds and runs fine with these changes.
=> Various minor tidy ups

src/backends/perf_pt/decode.c, src/backends/perf_pt/mod.rs, tests/pt_chdir_rel.rs
Without this change, if the process to be traced was invoked with a relative path and changes directory before decoding a trace, then the PT backend would try to create a libipt image using a (stale) relative path for the main binary's object.
As discussed with @ltratt, we fix this is a hacky fashion for now, using current_exe() to get an absolute path to the executable file. We shouldn't rely on this in the long term.
=> Ensure that hwtracer can decode PT traces in the face of chdir().

examples/simple_example.rs, src/collect/mod.rs, src/collect/perf/mod.rs, src/decode/libipt/mod.rs, src/decode/mod.rs, tests/pt_chdir_rel.rs
Before this change, `ThreadTraceCollector` was exposed to the consumer of the hwtracer API. Calling `TraceCollector::thread_tracer()` would give back a fresh instance each time. This API would allow the user request multiple `ThreadTraceCollector`s on the same thread and start them all "collecting traces" concurrently. This leads to chaos as any given thread can only be traced at most once at a time.
Until now we've swept this under the rug, warning the user not to do the naughty thing unless they want to invoke UB, but the API still allows it to happen.
This change hides `ThreadTraceCollector`s from the public API entirely, leaving `TraceCollector`s to manage thread local instances of `ThreadTraceCollector`.
The user now starts and stops trace collection of a thread with …
=> Make the API more thread-safe.
